-- tables
-- Table: AGENCIA
CREATE TABLE AGENCIA (
    IDAGEN integer  NOT NULL,
    RUC_AGEN char(11)  NOT NULL,
    DIREC_AGEN varchar2(30)  NOT NULL,
    CONSTRAINT AGENCIA_pk PRIMARY KEY (IDAGEN)
) ;

-- Table: ALQUILER
CREATE TABLE ALQUILER (
    IDALQUI integer  NOT NULL,
    IDINQ integer  NOT NULL,
    FECHINIALQUI date  NOT NULL,
    FECHFINALQUI date  NOT NULL,
    IMPOALQIU integer  NOT NULL,
    FIANALQUI integer  NOT NULL,
    FECHFIRMALQUI date  NOT NULL,
    IDVIVI integer  NOT NULL,
    RENOALQUI integer  NOT NULL,
    CONSTRAINT ALQUILER_pk PRIMARY KEY (IDALQUI)
) ;

-- Table: INQUILINO
CREATE TABLE INQUILINO (
    IDINQ integer  NOT NULL,
    NOMINQ varchar2(30)  NULL,
    APEINQ varchar2(30)  NULL,
    DNIINQ char(8)  NULL,
    TELINQ char(9)  NULL,
    FECNACINQ date  NULL,
    CONSTRAINT INQUILINO_pk PRIMARY KEY (IDINQ)
) ;

-- Table: PROPIETARIO
CREATE TABLE PROPIETARIO (
    IDPRO integer  NOT NULL,
    NOM_PER varchar2(30)  NOT NULL,
    APE_PER varchar2(30)  NOT NULL,
    DNI_PER char(8)  NOT NULL,
    TELF_PER char(9)  NOT NULL,
    DIREC_PER varchar2(30)  NULL,
    EMIAL_PER varchar2(50)  NULL,
    CONSTRAINT PROPIETARIO_pk PRIMARY KEY (IDPRO)
) ;

-- Table: VIVIENDA
CREATE TABLE VIVIENDA (
    IDVIVI integer  NOT NULL,
    CALLVIVI varchar2(30)  NOT NULL,
    NUMVIVI integer  NOT NULL,
    CODPOSVIVI integer  NOT NULL,
    PISOVIVI integer  NOT NULL,
    POBLAVIVI varchar2(30)  NOT NULL,
    DESCVIVI varchar2(500)  NOT NULL,
    IDA_GEN integer  NOT NULL,
    IDPRO integer  NOT NULL,
    CONSTRAINT VIVIENDA_pk PRIMARY KEY (IDVIVI)
) ;

-- foreign keys
-- Reference: ALQUILER_ALQUILER (table: ALQUILER)
ALTER TABLE ALQUILER ADD CONSTRAINT ALQUILER_ALQUILER
    FOREIGN KEY (RENOALQUI)
    REFERENCES ALQUILER (IDALQUI);

-- Reference: ALQUILER_INQUILINO (table: ALQUILER)
ALTER TABLE ALQUILER ADD CONSTRAINT ALQUILER_INQUILINO
    FOREIGN KEY (IDINQ)
    REFERENCES INQUILINO (IDINQ);

-- Reference: ALQUILER_VIVIENDA (table: ALQUILER)
ALTER TABLE ALQUILER ADD CONSTRAINT ALQUILER_VIVIENDA
    FOREIGN KEY (IDVIVI)
    REFERENCES VIVIENDA (IDVIVI);

-- Reference: VIVIENDA_AGENCIA (table: VIVIENDA)
ALTER TABLE VIVIENDA ADD CONSTRAINT VIVIENDA_AGENCIA
    FOREIGN KEY (IDA_GEN)
    REFERENCES AGENCIA (IDAGEN);

-- Reference: VIVIENDA_PROPIETARIO (table: VIVIENDA)
ALTER TABLE VIVIENDA ADD CONSTRAINT VIVIENDA_PROPIETARIO
    FOREIGN KEY (IDPRO)
    REFERENCES PROPIETARIO (IDPRO);

-- End of file.

