CREATE DATABASE CINE;

USE CINE;

CREATE TABLE COMBO (
    IDCOM int  NOT NULL IDENTITY(1,1),
    NOMCOM varchar(30)  NOT NULL,
    PRECOM decimal(10,7)  NOT NULL,
    CONSTRAINT COMBO_pk PRIMARY KEY  (IDCOM)
);

CREATE TABLE COMBO_DETALLE (
    IDCOMDET int  NOT NULL IDENTITY(1,1),
    IDCOM int  NOT NULL,
    IDPRO int  NOT NULL,
    CANTPRO int  NOT NULL,
    CONSTRAINT COMBO_DETALLE_pk PRIMARY KEY  (IDCOMDET)
);

CREATE TABLE GENERO_PELICULA (
    IDGEN int  NOT NULL IDENTITY(1,1),
    GEN varchar(30)  NOT NULL,
    CONSTRAINT GENERO_PELICULA_pk PRIMARY KEY  (IDGEN)
);

CREATE TABLE PELICULA (
    IDPEL int  NOT NULL IDENTITY(1,1),
    NOMPEL varchar(30)  NOT NULL,
    SALAPEL int  NOT NULL,
    FECHESTRENO date  NOT NULL,
    FECHTERMINO date  NOT NULL,
    IDGEN int  NOT NULL,
    CONSTRAINT PELICULA_pk PRIMARY KEY  (IDPEL)
);

CREATE TABLE PERSONAL (
    IDPER int  NOT NULL IDENTITY(1,1),
    NOMPER varchar(30)  NOT NULL,
    APEPER varchar(30)  NOT NULL,
    DNIPER char(8)  NOT NULL,
    TELPER char(9)  NOT NULL,
    TIPPER char(2)  NOT NULL,
    CONSTRAINT PERSONAL_pk PRIMARY KEY  (IDPER)
);

CREATE TABLE PRODUCTOS (
    IDPRO int  NOT NULL IDENTITY(1,1),
    NOMPRO varchar(30)  NOT NULL,
    CONSTRAINT PRODUCTOS_pk PRIMARY KEY  (IDPRO)
);

CREATE TABLE VENTA (
    IDVENT int  NOT NULL IDENTITY(1,1),
    IDPER int  NOT NULL,
    FECVENT date  NOT NULL,
    TOTAVENT decimal(10,7)  NOT NULL,
    TIPVENT char(1)  NOT NULL,
    CONSTRAINT VENTA_pk PRIMARY KEY  (IDVENT)
);

CREATE TABLE VENTA_COMBOS (
    IDVENCOM int  NOT NULL IDENTITY(1,1),
    IDCOM int  NOT NULL,
    VENTA_IDVENT int  NOT NULL,
    CONSTRAINT VENTA_COMBOS_pk PRIMARY KEY  (IDVENCOM)
);

CREATE TABLE VENTA_ENTRADA (
    IDVENTDET int  NOT NULL IDENTITY(1,1),
    IDPEL int  NOT NULL,
    VENTA_IDVENT int  NOT NULL,
    CONSTRAINT VENTA_ENTRADA_pk PRIMARY KEY  (IDVENTDET)
);

ALTER TABLE COMBO_DETALLE ADD CONSTRAINT COMBO_DETALLE_COMBO
    FOREIGN KEY (IDCOM)
    REFERENCES COMBO (IDCOM);

ALTER TABLE COMBO_DETALLE ADD CONSTRAINT COMBO_DETALLE_Productos
    FOREIGN KEY (IDPRO)
    REFERENCES PRODUCTOS (IDPRO);

ALTER TABLE VENTA_ENTRADA ADD CONSTRAINT DETALLE_VENTA_PELICULA
    FOREIGN KEY (IDPEL)
    REFERENCES PELICULA (IDPEL);

ALTER TABLE PELICULA ADD CONSTRAINT PELICULA_GENERO_PELICULA
    FOREIGN KEY (IDGEN)
    REFERENCES GENERO_PELICULA (IDGEN);

ALTER TABLE VENTA_COMBOS ADD CONSTRAINT VENTA_COMBOS_COMBO
    FOREIGN KEY (IDCOM)
    REFERENCES COMBO (IDCOM);

ALTER TABLE VENTA_COMBOS ADD CONSTRAINT VENTA_COMBOS_VENTA
    FOREIGN KEY (VENTA_IDVENT)
    REFERENCES VENTA (IDVENT);

ALTER TABLE VENTA_ENTRADA ADD CONSTRAINT VENTA_ENTRADA_VENTA
    FOREIGN KEY (VENTA_IDVENT)
    REFERENCES VENTA (IDVENT);

ALTER TABLE VENTA ADD CONSTRAINT VENTA_PERSONAL
    FOREIGN KEY (IDPER)
    REFERENCES PERSONAL (IDPER);

